services:

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: nexusai-backend
    command:
      - .venv/bin/python
      - -m
      - uvicorn
      - app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
      - --reload-dir
      - /app/app
    env_file:
      - path: ../.env
        required: false
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app/app
    depends_on:
      - postgres
      - redis
      - qdrant
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: nexusai-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: nexusai-qdrant

    ports:
      - "6333:6333"
      - "6334:6334"

    volumes:
      - qdrant_data:/qdrant/storage

    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: nexusai-redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    restart: unless-stopped

volumes:
  postgres_data:  
  qdrant_data:
  redis_data:
